### ISSUE TITLE
Cannot get Ping() to work

### ISSUE THREAD

**Issue by jhinrichsen** [jfrog/jfrog-client-go#79]
I have a working jfrog-cli setup on my machine, which i want to reproduce in Go code.

```
$ jfrog rt ping
Ok
````

Trying to re-use this working setup in a Go program instead of the commandline, i waded through jfrog-cli-go, jfrog-go, and jfrog-client-go without any success. Documentation suggests to use the artifactory service manager from jfrog-client-go, but the only place i found that knows how to instantiate configs from $HOME/.jfrog/jfrog-cli.conf is in jfrog-cli-go, unfortunately the config in client and cli are not interchangeable.

Trying to manually copy struct members `Url`, `User` and `Password` from cli to client struct results in a sigsev.

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x9501a2]

goroutine 1 [running]:
github.com/jfrog/jfrog-client-go/artifactory/services.(*PingService).Ping(0xc00012be78, 0x0, 0x0, 0x0, 0xc00012e4b0, 0x0)
        go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.5.0/artifactory/services/ping.go:39 +0x42
github.com/jfrog/jfrog-client-go/artifactory.(*ArtifactoryServicesManager).Ping(0xc00012e4b0, 0xb9f740, 0xc0000c6640, 0x0, 0x0, 0xc00012e4b0)
        go/pkg/mod/github.com/jfrog/jfrog-client-go@v0.5.0/artifactory/manager.go:166 +0x79
main.main()
        work/jfrog-lib/main.go:49 +0x36f
````
What i am missing is a clear, minimal, concise, working example of a main.go that can Ping() the artifactory server. My trial and error path currently looks like this:

````
package main

// github.com/jfrog/jfrog-cli-go/
// "github.com/jfrog/jfrog-cli-go/jfrog-cli/commands/generic"
// "github.com/jfrog/jfrog-cli-go/jfrog-cli/artifactory/generic"

import (
        "fmt"

        "github.com/jfrog/jfrog-cli-go/jfrog-cli/utils/config"
        "github.com/jfrog/jfrog-client-go/artifactory"
        "github.com/jfrog/jfrog-client-go/artifactory/auth"
)

func main() {
        cs, err := config.GetAllArtifactoryConfigs()
        if err != nil {
                fmt.Errorf("error reading configuration: %v\n", err)
        }
        var configDetails *config.ArtifactoryDetails
        for _, c := range cs {
                if c.IsDefault {
                        fmt.Printf("default entry: %+v\n", c)
                        configDetails = c
                }
        }
        if !configDetails.IsDefault {
                fmt.Errorf("configuration does not contain default entry")
        }

        authDetails := auth.NewArtifactoryDetails()
        authDetails.SetUrl(configDetails.Url)
        authDetails.SetUser(configDetails.User)
        authDetails.SetPassword(configDetails.Password)

        // Ping
        // rtManager, err := artifactory.New(dc)
        // client := httpclient.New()
        // ps := services.NewPingService(&client)
        // ps.Ping()
        config, _ := artifactory.NewConfigBuilder().SetInsecureTls(true).Build()
        asm, err := artifactory.New(&authDetails, config)
        if err != nil {
                fmt.Errorf("error creating artifactory services manager: %v\n",
                        err)
        }
        asm.Ping()
        /*
                rtManager, err := artifactory.New(rtDetails, serviceConfig)

                params := services.NewSearchParams()
                // params.Pattern = "repo/"
                params.Recursive = true

                searchResult := rtManager.SearchFiles(params)
        */

        /* Using the jfrog-cli-go package does not find generic search command
        s := generic.NewSearchCommand()
        fmt.Printf("search: %+v\n", s)
        */
}
````

**Comment by chiragg6** [comment]
any updates on the above mentioned issue?

**Comment by chiragg6** [comment]
Hi, got the solution.
Just initialize logger using utils/log.NewLogger

**Comment by jhinrichsen** [comment]
No worries. The new "jfrog-cli-core" library, released end of September, is just fine.
